name: health_sync
description: "Kocaeli Üniversitesi Bilgisayar Mühendisliği Mobil Programlama dersi projesi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.2
  dio: ^5.3.2
  jwt_decoder: ^2.0.1
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.0
  awesome_notifications: ^0.8.3  # Bunu ekleyelim
  rxdart: ^0.27.7
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Bu kısmı ekleyin
dependency_overrides:
  flutter_local_notifications_platform_interface: ^6.0.0
  flutter_local_notifications_linux: ^0.3.0

flutter:
  uses-material-design: true