name: health_sync
description: "Kocaeli Üniversitesi Bilgisayar Mühendisliği Mobil Programlama dersi projesi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Temel UI ve İkonlar
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0

  # Depolama ve Veritabanı
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  path: ^1.9.0

  # State Management
  provider: ^6.1.2

  # API ve Network
  dio: ^5.3.2

  # Authentication
  jwt_decoder: ^2.0.1
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700